### ISSUE TITLE
TypeError after upgrade 1.0.13 -> 1.0.14

### ISSUE THREAD

**Issue by don-bluelinegrid** [Vheissu/aurelia-configuration#77]
After upgrading from 1.0.13 to 1.0.14, I am seeing this error:
```
bluebird.js:5236 TypeError: customConfig.configure is not a function
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15605:27
From previous event:
    at config (http://localhost:9000/aurelia-bootstrap.bundle.js:15604:46)
    at handleApp (http://localhost:9000/aurelia-bootstrap.bundle.js:15595:10)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15623:9
From previous event:
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15620:44
From previous event:
    at run (http://localhost:9000/aurelia-bootstrap.bundle.js:15617:24)
    at Object.<anonymous> (http://localhost:9000/aurelia-bootstrap.bundle.js:15642:1)
    at Object.aurelia-bootstrapper-webpack (http://localhost:9000/aurelia-bootstrap.bundle.js:15643:30)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at Object.313 (http://localhost:9000/aurelia-bootstrap.bundle.js:14480:1)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:57:38)
    at 111 (http://localhost:9000/aurelia-bootstrap.bundle.js:140:18)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:143:10
```

Using v 1.0.13 I never saw this error.

**Comment by Vheissu** [comment]
Closing this as two new versions have been released since.
